server.port=7060

spring.datasource.url=jdbc:postgresql://localhost:5432/sheets
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.web.socket.stomp.endpoint=/ws
spring.web.socket.stomp.broker=/topic

jwt.secret=SheetsAppSecretKeyForJWTTokenGeneration2026VeryLongSecretKeyMustBeAtLeast256Bits
jwt.expiration-hours=24

logging.file.name=../app.log
logging.level.root=INFO
logging.level.com.sheets=DEBUG